#!/bin/bash

pub_key=/etc/pub/RSApub.key
pri_key=/etc/priv/RSAprivate.key

if [[ $# -eq 0 ]]; then
  echo "Error: Please provide an IP address."
  exit 1
fi

if [[ $# -gt 1 ]]; then
  echo "Warning: Only the last argument will be considered as the IP address."
fi

# check for key file
if [ ! -f "${pub_key}" ] || [ ! -f "${pri_key}" ]; then 
    echo "Please generate pair key file"
    exit 1
fi

IP="${@: -1}"
OPTIONS="${@: 0: $# }"
FTP_BIN=/usr/bin/ftpclient

echo "Connect to server with IP address: ${IP}"
echo "Options: ${OPTIONS}"

function __checkIP()
{
    regexIP=[1-9][0-9]{2}.\d{1,3}.\d{1,3}.\d{1,3}

    local IP="$1"

    if [[ ! ${IP} =~ ${regexIP} ]]; then
        notfound=$(host ${IP} | grep "not found")
        if [ ${notfound} ] ; then  
            echo "IP address is unidentified"
            exit 1
        fi
    fi
}

function __main()
{
    __checkIP ${IP}
    ${FTP_BIN} ${IP} ${OPTIONS}
}

__main



