#include "cmd.h"
#include "data.h"
#include "control.h"

command commands[] = {
    {"get", 500, get, "get file from remote server. Usage: get <remote file name>"},
    {"put", 501, put, "send file to remote server. Usage: put <local file name>"},
    {"recv", 502, NULL},
    {"send", 503, NULL},
    {"append", 504, data_append, "append a local file to remote file on server." 
                                 "Usage: append <local file name> <remote file name>"},
    {"case", 505, NULL},
    {"cd", 506, change_dir, "change remote path. Usage: cd <remote path>"},
    {"chmod", 507, change_mode, "change file/dir mode on remote server. Usage: chmod <remote file/path>"},
    {"delete", 508, delete_remote_file, "delete remote file on server. Usage: delete <remote file>"},
    {"dir", 509, NULL},
    {"lcd", 510, NULL},
    {"ls", 511, list_remote_dir, "list remote dir. Usage: ls <remote dir>"},
    {"idle", 512, idle_set_remote, "set idle time out. Usage: idle <time out value>"},
    {"mdelete", 513, NULL},
    {"mdir", 514, NULL },
    {"mget", 515, NULL},
    {"mkdir", 516, NULL},
    {"mls", 517, NULL},
    {"modtime", 518, remote_modtime, "get remote modtime. Usage: modtime"},
    {"mput", 519, NULL},
    {"newer", 520, data_newer, "If local file is older, get the file from remote. Usage: newer <file>"},
    {"nlist", 521, NULL},
    {"prompt", 522, NULL},
    {"pwd", 523, NULL},
    {"qc", 524, NULL},
    {"reget", 525, data_reget, "reget the file from the latest cursor position. Usage: reget <remote file name>"},
    {"rename", 526, remote_change_name, "change remote file name. Usage: rename <old name> <new name>"},
    {"reset", 527, NULL},
    {"restart", 528, NULL},
    {"rhelp", 529, NULL},
    {"rmdir", 530, remove_remote_dir, "remove remote dir. Usage: rmdir <remote dir>"},
    {"rstatus", 531, NULL},
    {"size", 532, remote_get_size, "get remote file's size. Usage: size <remote file>"},
    {"status", 533, NULL},
    {"system", 534, NULL},
    {"tick", 535, NULL},
    {"ipv4_op", 536, NULL},
    {"ipv6_op", 537, NULL},
    {"passmode", 538, NULL},
    {"int_off", 539, NULL},
    {"aulog_dis", 540, NULL},
    {"glob_dis", 541, NULL},
    {"verbose_enb", 542, NULL},
    {"debug_enb", 543, NULL},
    {"clear", 544, NULL},
    { NULL, NULL, NULL }
};


