#include "cmd.h"
#include "data.h"
#include "control.h"

command commands[] = {
    {"get", 500, get},
    {"put", 501, put},
    {"recv", 502, NULL},
    {"send", 503, NULL},
    {"append", 504, data_append},
    {"case", 505, NULL},
    {"cd", 506, change_dir},
    {"chmod", 507, change_mode},
    {"delete", 508, delete_remote_file},
    {"dir", 509, NULL},
    {"lcd", 510, NULL},
    {"ls", 511, list_remote_dir},
    {"idle", 512, idle_set_remote},
    {"mdelete", 513, NULL},
    {"mdir", 514, NULL },
    {"mget", 515, NULL},
    {"mkdir", 516, NULL},
    {"mls", 517, NULL},
    {"modtime", 518, remote_modtime},
    {"mput", 519, NULL},
    {"newer", 520, data_newer},
    {"nlist", 521, NULL},
    {"prompt", 522, NULL},
    {"pwd", 523, NULL},
    {"qc", 524, NULL},
    {"reget", 525, data_reget},
    {"rename", 526, remote_change_name},
    {"reset", 527, NULL},
    {"restart", 528, NULL},
    {"rhelp", 529, NULL},
    {"rmdir", 530, remove_remote_dir},
    {"rstatus", 531, NULL},
    {"size", 532, remote_get_size},
    {"status", 533, NULL},
    {"system", 534, NULL},
    {"tick", 535, NULL},
    {"ipv4_op", 536, NULL},
    {"ipv6_op", 537, NULL},
    {"passmode", 538, NULL},
    {"int_off", 539, NULL},
    {"aulog_dis", 540, NULL},
    {"glob_dis", 541, NULL},
    {"verbose_enb", 542, NULL},
    {"debug_enb", 543, NULL},
    {"clear", 544, NULL},
    { NULL, NULL, NULL }
};


